import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRaidEngine } from '../../build/super_mega_raid_simulator.js';
import { PythonRandom } from '../../build/random.js';
import { parse_replay_text } from '../../build/battle_replay.js';
import { build_playback } from '../../build/battle_playback.js';
import { run_simulations,battle_config } from '../../build/website_api.js';
import { TurnService } from '../../build/turn_service.js';
import { literal,seconds_to_tick } from '../../build/text.js';
const catalog=JSON.parse(readFileSync(new URL('../../simulator/calculator_data.json',import.meta.url)));
const request={boss:'STARMIE',boss_fast_move:'Hidden Power',boss_charged_move:'Hydro Pump',raid_difficulty:'Tier 3',team:[{name:'MEWTWO',fast_move:'Confusion',charged_move:'Psystrike',level:50}],random_seed:'9223372036854775807'};
const preamble='Raid: Tier 4\nBoss: STARMIE_MEGA; fast=Water Gun; charged=Hydro Pump\nTeams:\np1: Armored Mewtwo / Confusion / Psystrike / L50 / 15-15-15\nMove codes: co=Confusion; ps=Psystrike\nEvents:\n';
test('single and batch browser API preserve 63-bit seeds and Hidden Power',()=>{
 const first=run_simulations(request,catalog),second=run_simulations(request,catalog);
 assert.deepEqual(first,second);assert.equal(first.random_seed,request.random_seed);
 assert(!['Normal','Fairy'].includes(first.boss_fast_type));
 const playback=build_playback(first.replay_text,catalog);
 assert.equal(playback.source,'verified_simulation');assert.deepEqual(playback.warnings,[]);
 const batch=run_simulations({...request,simulation_count:16},catalog);
 assert.equal(batch.total_battles,16);
 const types=batch.movesets[0].hidden_power_types;
 assert.equal(Object.values(types).reduce((a,b)=>a+b),16);assert(Object.keys(types).length>1);
});
test('engines and simulations have independent state and configurations',()=>{
 const a=createRaidEngine(battle_config(request,catalog),catalog);
 const b=createRaidEngine(battle_config({...request,boss:'KYOGRE',boss_fast_move:'Waterfall',raid_difficulty:'Tier 5'},catalog),catalog);
 assert.equal(a.BOSS_HP,3600);assert.equal(b.BOSS_HP,15000);
 const make=e=>new e.Simulation(Object.values(e.BOSS_FAST_MOVES)[0],Object.values(e.BOSS_CHARGED_MOVES)[0],new PythonRandom(42));
 const one=make(a),two=make(a);one.players[0].energy=100;
 assert.equal(two.players[0].energy,0);assert.notEqual(one.players[0],two.players[0]);
 one.run();assert.equal(two.boss_hp,3600);
 assert.equal(a.BOSS_FAST_MOVES['Hidden Power'].move_type,'Normal');
});
test('replay timestamps, legacy tuples, and malformed input are safe',()=>{
 assert.equal(seconds_to_tick('1.500000000000000000000',1),3);
 for(const invalid of ['0.25','1.50000000000000000001','9999999999999999999999']) assert.throws(()=>seconds_to_tick(invalid,1));
 assert.deepEqual(literal("[('Mewtwo', True, None, 50.5)]"),[['Mewtwo',true,null,50.5]]);
 assert.throws(()=>literal("__import__('os').system('anything')"));
 assert.throws(()=>literal('['.repeat(100)+'0'+']'.repeat(100)),/nesting/);
 assert.throws(()=>parse_replay_text(preamble+'+0p1:co'),/absolute/);
 assert.throws(()=>parse_replay_text(preamble+'t0p2:co'),/undefined p2/);
 assert.throws(()=>parse_replay_text(preamble+'t0p1:r2'),/Party presets/);
 assert.throws(()=>parse_replay_text(preamble+'t0p1:s2'),/only has 1/);
 assert.throws(()=>build_playback(preamble+'t0p1:ps',catalog),/needs 50 energy/);
 assert.throws(()=>build_playback(preamble+'t0p1:q\n+1p1:s1',catalog),/must rejoin/);
 const frame=build_playback(preamble+'t0p1:co\n+0b:f',catalog).frames.at(-1);
 assert.equal(frame.boss_hp,8993);assert.equal(frame.players[0].energy,15);
});
test('application boundary rejects invalid inputs before starting calculations',()=>{
 for(const simulation_count of [0,101,1.5,true,NaN]) assert.throws(()=>battle_config({...request,simulation_count},catalog));
 for(const random_seed of ['1.5','9223372036854775808','-1',9007199254740992]) assert.throws(()=>battle_config({...request,random_seed},catalog));
 assert.throws(()=>battle_config({...request,team:[{...request.team[0],fast_move:'Water Gun'}]},catalog),/legal moves/);
 assert.throws(()=>battle_config({...request,boss:'MEW',boss_fast_move:'Pound',boss_charged_move:'Psychic',boss_moveset_mode:'all',simulation_count:2},catalog),/limit is 500/);
 assert.throws(()=>run_simulations({...request,zacian_adventure_effect:true,behemoth_bash_adventure_effect:true},catalog),/Only one Adventure Effect/);
});
test('accepted manual turns persist, restore, reject stale steps, and roll back failed saves',async()=>{
 const saved=new Map();let rejectSave=false;
 const service=new TurnService(catalog,async record=>{if(rejectSave)throw new Error('Save failed');saved.set(record.id,structuredClone(record));});
 const start=await service.start({...request,random_seed:42});
 const step=await service.update({session_id:start.session_id,expected_tick:0,action:'fast'});
 assert.equal(step.tick,1);assert.equal(saved.get(start.session_id).revision,1);
 await assert.rejects(service.update({session_id:start.session_id,expected_tick:0,action:'wait'}),/already advanced/);
 rejectSave=true;
 await assert.rejects(service.update({session_id:start.session_id,expected_tick:1,action:'wait'}),/Save failed/);
 assert.equal(saved.get(start.session_id).tick,1);
 rejectSave=false;
 const next=await service.update({session_id:start.session_id,expected_tick:1,action:'wait'});assert.equal(next.tick,2);
 const restored=await new TurnService(catalog).restore(saved.get(start.session_id));
 assert.deepEqual(restored,next);
 const stopped=await service.update({session_id:start.session_id,expected_tick:2},true);
 assert.equal(stopped.status,'stopped');
 assert.equal(build_playback(stopped.replay_text,catalog).duration_ticks,2);
});
